server:
  port: 8283
http:
  logging:
    enabled: true
    log-body: true
    log-level: WARN
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: aspect-service